name: atime performance tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'R/**'
      - '.ci/atime/**'

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: Anirban166/Autocomment-atime-results@v1.5.0
        with:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
