name: atime performance tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'R/**'
      - '.ci/atime/**'

jobs:
  comment:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    env:
      GITHUB_PAT: ${{ secrets.PAT_GITHUB_PR }}
      repo_token: ${{ secrets.PAT_GITHUB_PR }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: install package
        run: R CMD INSTALL .
      - uses: Anirban166/Autocomment-atime-results@v1.4.3