name: Test Suite
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test-suite: [ renderer, compiler, CRAN ]

    name: Test Suite ${{ matrix.test-suite }}
    env: 
      TEST_SUITE: ${{ matrix.test-suite }}
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
      GH_ACTION: "ENABLED"
      COLLECT_COVERAGE: "TRUE"
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: install and update texlive
        run: /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt update -y -qq
      - run: /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt install tidy texlive texlive-fonts-extra -y
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install coverage tools
        run: npm install --no-save puppeteer-to-istanbul nyc

      - name: install package
        run: R CMD INSTALL .

      - name: git config user.name 
        run: git config --global user.name "GitHub Actions"

      - name: git config user.email
        run: git config --global user.email toby.hocking@r-project.org
      
      - name: run tests
        run: |
          if [ "$TEST_SUITE" == "CRAN" ]; then
            bash build.sh
          elif [ "$TEST_SUITE" == "compiler" ]; then
            Rscript -e "source('tests/testthat.R', chdir = TRUE)"
            Rscript -e 'covr::codecov(quiet = TRUE)'
          else
            Rscript -e "source('tests/testthat.R', chdir = TRUE)"
          fi

      - name: Process JS coverage and upload to Codecov
        if: matrix.test-suite == 'renderer'
        run: |
          # Convert coverage using puppeteer-to-istanbul
          if [ -f "tests/testthat/js-coverage.json" ]; then
            echo "Converting JS coverage data..."
            npx puppeteer-to-istanbul tests/testthat/js-coverage.json --coverage-type v8
            npx nyc report --reporter=lcov --report-dir=coverage

            # Upload to Codecov
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -f coverage/lcov.info -t ${{ secrets.CODECOV_TOKEN }} --flags javascript
          else
            echo "No JS coverage file found"
            exit 1
          fi