name: Test Suite
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test-suite: [ renderer, compiler, CRAN ]

    name: Test Suite ${{ matrix.test-suite }}
    env: 
      TEST_SUITE: ${{ matrix.test-suite }}
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
      GH_ACTION: "ENABLED"
    steps:
      - uses: actions/checkout@v3
      - name: install and update texlive
        run: /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt update -y -qq
      - run: /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt install tidy texlive texlive-fonts-extra -y
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: install package
        run: R CMD INSTALL .

      - name: git config user.name 
        run: git config --global user.name "GitHub Actions"

      - name: git config user.email
        run: git config --global user.email toby.hocking@r-project.org
      
      - name: run tests
        run: if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi

  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install covr
        run: Rscript -e 'install.packages("covr")'

      - name: Install Node.js and puppeteer-to-istanbul
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g puppeteer-to-istanbul nyc

      - name: Run R tests and collect coverage
        run: |
          cd tests
          Rscript run-coverage.R
          cd ../

      - name: Run R tests (renderer) to collect JS coverage
        env:
          TEST_SUITE: renderer
        run: |
          cd tests
          Rscript ../tests/testthat.R
          cd ../

      - name: Convert JS coverage to lcov
        run: |
          npx puppeteer-to-istanbul js-coverage.json
          npx nyc report --reporter=lcov --report-dir=coverage

      - name: Download Codecov uploader
        run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - name: Make uploader executable
        run: chmod +x codecov

      - name: Upload coverage to Codecov
        # env:
         
        run: |
          ./codecov -f coverage.xml -f coverage/lcov.info